language: csharp
sudo: false

before_install:
  - nuget install -OutputDirectory packages
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c specflow.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=9941"

script:
  - msbuild /t:BuildNUnitFiles
  - msbuild
  - msbuild /t:Test

after_script:
  - hiptest-publisher -c specflow.conf --token=$SECRET_TOKEN --push=TestResult.xml --test-run-id=9941
